// api/proto/deposit.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: deposit.proto

package cryptopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepositService_GetUserDeposits_FullMethodName    = "/crypto.v1.DepositService/GetUserDeposits"
	DepositService_GetDeposit_FullMethodName         = "/crypto.v1.DepositService/GetDeposit"
	DepositService_GetPendingDeposits_FullMethodName = "/crypto.v1.DepositService/GetPendingDeposits"
)

// DepositServiceClient is the client API for DepositService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DepositService handles deposit monitoring and tracking
type DepositServiceClient interface {
	// Get user deposits
	GetUserDeposits(ctx context.Context, in *GetUserDepositsRequest, opts ...grpc.CallOption) (*GetUserDepositsResponse, error)
	// Get deposit by ID
	GetDeposit(ctx context.Context, in *GetDepositRequest, opts ...grpc.CallOption) (*GetDepositResponse, error)
	// Get pending deposits (waiting confirmations)
	GetPendingDeposits(ctx context.Context, in *GetPendingDepositsRequest, opts ...grpc.CallOption) (*GetPendingDepositsResponse, error)
}

type depositServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositServiceClient(cc grpc.ClientConnInterface) DepositServiceClient {
	return &depositServiceClient{cc}
}

func (c *depositServiceClient) GetUserDeposits(ctx context.Context, in *GetUserDepositsRequest, opts ...grpc.CallOption) (*GetUserDepositsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDepositsResponse)
	err := c.cc.Invoke(ctx, DepositService_GetUserDeposits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) GetDeposit(ctx context.Context, in *GetDepositRequest, opts ...grpc.CallOption) (*GetDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositResponse)
	err := c.cc.Invoke(ctx, DepositService_GetDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositServiceClient) GetPendingDeposits(ctx context.Context, in *GetPendingDepositsRequest, opts ...grpc.CallOption) (*GetPendingDepositsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingDepositsResponse)
	err := c.cc.Invoke(ctx, DepositService_GetPendingDeposits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositServiceServer is the server API for DepositService service.
// All implementations must embed UnimplementedDepositServiceServer
// for forward compatibility.
//
// DepositService handles deposit monitoring and tracking
type DepositServiceServer interface {
	// Get user deposits
	GetUserDeposits(context.Context, *GetUserDepositsRequest) (*GetUserDepositsResponse, error)
	// Get deposit by ID
	GetDeposit(context.Context, *GetDepositRequest) (*GetDepositResponse, error)
	// Get pending deposits (waiting confirmations)
	GetPendingDeposits(context.Context, *GetPendingDepositsRequest) (*GetPendingDepositsResponse, error)
	mustEmbedUnimplementedDepositServiceServer()
}

// UnimplementedDepositServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepositServiceServer struct{}

func (UnimplementedDepositServiceServer) GetUserDeposits(context.Context, *GetUserDepositsRequest) (*GetUserDepositsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDeposits not implemented")
}
func (UnimplementedDepositServiceServer) GetDeposit(context.Context, *GetDepositRequest) (*GetDepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeposit not implemented")
}
func (UnimplementedDepositServiceServer) GetPendingDeposits(context.Context, *GetPendingDepositsRequest) (*GetPendingDepositsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingDeposits not implemented")
}
func (UnimplementedDepositServiceServer) mustEmbedUnimplementedDepositServiceServer() {}
func (UnimplementedDepositServiceServer) testEmbeddedByValue()                        {}

// UnsafeDepositServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepositServiceServer will
// result in compilation errors.
type UnsafeDepositServiceServer interface {
	mustEmbedUnimplementedDepositServiceServer()
}

func RegisterDepositServiceServer(s grpc.ServiceRegistrar, srv DepositServiceServer) {
	// If the following call panics, it indicates UnimplementedDepositServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepositService_ServiceDesc, srv)
}

func _DepositService_GetUserDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDepositsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).GetUserDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_GetUserDeposits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).GetUserDeposits(ctx, req.(*GetUserDepositsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_GetDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).GetDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_GetDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).GetDeposit(ctx, req.(*GetDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositService_GetPendingDeposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingDepositsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositServiceServer).GetPendingDeposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DepositService_GetPendingDeposits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositServiceServer).GetPendingDeposits(ctx, req.(*GetPendingDepositsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DepositService_ServiceDesc is the grpc.ServiceDesc for DepositService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepositService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.v1.DepositService",
	HandlerType: (*DepositServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserDeposits",
			Handler:    _DepositService_GetUserDeposits_Handler,
		},
		{
			MethodName: "GetDeposit",
			Handler:    _DepositService_GetDeposit_Handler,
		},
		{
			MethodName: "GetPendingDeposits",
			Handler:    _DepositService_GetPendingDeposits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deposit.proto",
}
