// api/proto/transaction. proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: transaction.proto

package cryptopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionService_EstimateNetworkFee_FullMethodName    = "/crypto.v1.TransactionService/EstimateNetworkFee"
	TransactionService_GetWithdrawalQuote_FullMethodName    = "/crypto.v1.TransactionService/GetWithdrawalQuote"
	TransactionService_Withdraw_FullMethodName              = "/crypto.v1.TransactionService/Withdraw"
	TransactionService_SweepUserWallet_FullMethodName       = "/crypto.v1.TransactionService/SweepUserWallet"
	TransactionService_SweepAllUsers_FullMethodName         = "/crypto.v1.TransactionService/SweepAllUsers"
	TransactionService_GetTransaction_FullMethodName        = "/crypto.v1.TransactionService/GetTransaction"
	TransactionService_GetUserTransactions_FullMethodName   = "/crypto.v1.TransactionService/GetUserTransactions"
	TransactionService_GetTransactionStatus_FullMethodName  = "/crypto.v1.TransactionService/GetTransactionStatus"
	TransactionService_GetPendingWithdrawals_FullMethodName = "/crypto.v1.TransactionService/GetPendingWithdrawals"
	TransactionService_ApproveWithdrawal_FullMethodName     = "/crypto.v1.TransactionService/ApproveWithdrawal"
	TransactionService_RejectWithdrawal_FullMethodName      = "/crypto.v1.TransactionService/RejectWithdrawal"
	TransactionService_GetWithdrawalApproval_FullMethodName = "/crypto.v1.TransactionService/GetWithdrawalApproval"
)

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransactionService handles crypto transactions
type TransactionServiceClient interface {
	// Estimate network fee (for accounting module)
	EstimateNetworkFee(ctx context.Context, in *EstimateNetworkFeeRequest, opts ...grpc.CallOption) (*EstimateNetworkFeeResponse, error)
	// Get withdrawal quote
	GetWithdrawalQuote(ctx context.Context, in *GetWithdrawalQuoteRequest, opts ...grpc.CallOption) (*GetWithdrawalQuoteResponse, error)
	// Execute withdrawal from system wallet (called by accounting)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	// Sweep operations (internal)
	SweepUserWallet(ctx context.Context, in *SweepUserWalletRequest, opts ...grpc.CallOption) (*SweepUserWalletResponse, error)
	// Sweep all user wallets for a specific asset and chain
	SweepAllUsers(ctx context.Context, in *SweepAllUsersRequest, opts ...grpc.CallOption) (*SweepAllUsersResponse, error)
	// Transaction queries
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// Get transactions for a user with filters and pagination
	GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsResponse, error)
	// Get transaction status by transaction ID
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error)
	// --- Admin operations for pending withdrawals ---
	GetPendingWithdrawals(ctx context.Context, in *GetPendingWithdrawalsRequest, opts ...grpc.CallOption) (*GetPendingWithdrawalsResponse, error)
	// Approve pending withdrawals (called by admin interface)
	ApproveWithdrawal(ctx context.Context, in *ApproveWithdrawalRequest, opts ...grpc.CallOption) (*ApproveWithdrawalResponse, error)
	// Reject pending withdrawals (called by admin interface)
	RejectWithdrawal(ctx context.Context, in *RejectWithdrawalRequest, opts ...grpc.CallOption) (*RejectWithdrawalResponse, error)
	// Get details of a pending withdrawal (for admin review)
	GetWithdrawalApproval(ctx context.Context, in *GetWithdrawalApprovalRequest, opts ...grpc.CallOption) (*GetWithdrawalApprovalResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) EstimateNetworkFee(ctx context.Context, in *EstimateNetworkFeeRequest, opts ...grpc.CallOption) (*EstimateNetworkFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateNetworkFeeResponse)
	err := c.cc.Invoke(ctx, TransactionService_EstimateNetworkFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetWithdrawalQuote(ctx context.Context, in *GetWithdrawalQuoteRequest, opts ...grpc.CallOption) (*GetWithdrawalQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalQuoteResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetWithdrawalQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, TransactionService_Withdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) SweepUserWallet(ctx context.Context, in *SweepUserWalletRequest, opts ...grpc.CallOption) (*SweepUserWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SweepUserWalletResponse)
	err := c.cc.Invoke(ctx, TransactionService_SweepUserWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) SweepAllUsers(ctx context.Context, in *SweepAllUsersRequest, opts ...grpc.CallOption) (*SweepAllUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SweepAllUsersResponse)
	err := c.cc.Invoke(ctx, TransactionService_SweepAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetUserTransactions(ctx context.Context, in *GetUserTransactionsRequest, opts ...grpc.CallOption) (*GetUserTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTransactionsResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetUserTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionStatusResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetPendingWithdrawals(ctx context.Context, in *GetPendingWithdrawalsRequest, opts ...grpc.CallOption) (*GetPendingWithdrawalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingWithdrawalsResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetPendingWithdrawals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ApproveWithdrawal(ctx context.Context, in *ApproveWithdrawalRequest, opts ...grpc.CallOption) (*ApproveWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveWithdrawalResponse)
	err := c.cc.Invoke(ctx, TransactionService_ApproveWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) RejectWithdrawal(ctx context.Context, in *RejectWithdrawalRequest, opts ...grpc.CallOption) (*RejectWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectWithdrawalResponse)
	err := c.cc.Invoke(ctx, TransactionService_RejectWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetWithdrawalApproval(ctx context.Context, in *GetWithdrawalApprovalRequest, opts ...grpc.CallOption) (*GetWithdrawalApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalApprovalResponse)
	err := c.cc.Invoke(ctx, TransactionService_GetWithdrawalApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations must embed UnimplementedTransactionServiceServer
// for forward compatibility.
//
// TransactionService handles crypto transactions
type TransactionServiceServer interface {
	// Estimate network fee (for accounting module)
	EstimateNetworkFee(context.Context, *EstimateNetworkFeeRequest) (*EstimateNetworkFeeResponse, error)
	// Get withdrawal quote
	GetWithdrawalQuote(context.Context, *GetWithdrawalQuoteRequest) (*GetWithdrawalQuoteResponse, error)
	// Execute withdrawal from system wallet (called by accounting)
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	// Sweep operations (internal)
	SweepUserWallet(context.Context, *SweepUserWalletRequest) (*SweepUserWalletResponse, error)
	// Sweep all user wallets for a specific asset and chain
	SweepAllUsers(context.Context, *SweepAllUsersRequest) (*SweepAllUsersResponse, error)
	// Transaction queries
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// Get transactions for a user with filters and pagination
	GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsResponse, error)
	// Get transaction status by transaction ID
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusResponse, error)
	// --- Admin operations for pending withdrawals ---
	GetPendingWithdrawals(context.Context, *GetPendingWithdrawalsRequest) (*GetPendingWithdrawalsResponse, error)
	// Approve pending withdrawals (called by admin interface)
	ApproveWithdrawal(context.Context, *ApproveWithdrawalRequest) (*ApproveWithdrawalResponse, error)
	// Reject pending withdrawals (called by admin interface)
	RejectWithdrawal(context.Context, *RejectWithdrawalRequest) (*RejectWithdrawalResponse, error)
	// Get details of a pending withdrawal (for admin review)
	GetWithdrawalApproval(context.Context, *GetWithdrawalApprovalRequest) (*GetWithdrawalApprovalResponse, error)
	mustEmbedUnimplementedTransactionServiceServer()
}

// UnimplementedTransactionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionServiceServer struct{}

func (UnimplementedTransactionServiceServer) EstimateNetworkFee(context.Context, *EstimateNetworkFeeRequest) (*EstimateNetworkFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateNetworkFee not implemented")
}
func (UnimplementedTransactionServiceServer) GetWithdrawalQuote(context.Context, *GetWithdrawalQuoteRequest) (*GetWithdrawalQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawalQuote not implemented")
}
func (UnimplementedTransactionServiceServer) Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Withdraw not implemented")
}
func (UnimplementedTransactionServiceServer) SweepUserWallet(context.Context, *SweepUserWalletRequest) (*SweepUserWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SweepUserWallet not implemented")
}
func (UnimplementedTransactionServiceServer) SweepAllUsers(context.Context, *SweepAllUsersRequest) (*SweepAllUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SweepAllUsers not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedTransactionServiceServer) GetUserTransactions(context.Context, *GetUserTransactionsRequest) (*GetUserTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTransactions not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*GetTransactionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedTransactionServiceServer) GetPendingWithdrawals(context.Context, *GetPendingWithdrawalsRequest) (*GetPendingWithdrawalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingWithdrawals not implemented")
}
func (UnimplementedTransactionServiceServer) ApproveWithdrawal(context.Context, *ApproveWithdrawalRequest) (*ApproveWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveWithdrawal not implemented")
}
func (UnimplementedTransactionServiceServer) RejectWithdrawal(context.Context, *RejectWithdrawalRequest) (*RejectWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectWithdrawal not implemented")
}
func (UnimplementedTransactionServiceServer) GetWithdrawalApproval(context.Context, *GetWithdrawalApprovalRequest) (*GetWithdrawalApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawalApproval not implemented")
}
func (UnimplementedTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {}
func (UnimplementedTransactionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_EstimateNetworkFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateNetworkFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).EstimateNetworkFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_EstimateNetworkFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).EstimateNetworkFee(ctx, req.(*EstimateNetworkFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetWithdrawalQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetWithdrawalQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetWithdrawalQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetWithdrawalQuote(ctx, req.(*GetWithdrawalQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_Withdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_SweepUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweepUserWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).SweepUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_SweepUserWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).SweepUserWallet(ctx, req.(*SweepUserWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_SweepAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweepAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).SweepAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_SweepAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).SweepAllUsers(ctx, req.(*SweepAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetUserTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetUserTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetUserTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetUserTransactions(ctx, req.(*GetUserTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetPendingWithdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingWithdrawalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPendingWithdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetPendingWithdrawals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPendingWithdrawals(ctx, req.(*GetPendingWithdrawalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ApproveWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ApproveWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_ApproveWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ApproveWithdrawal(ctx, req.(*ApproveWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_RejectWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).RejectWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_RejectWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).RejectWithdrawal(ctx, req.(*RejectWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetWithdrawalApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetWithdrawalApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionService_GetWithdrawalApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetWithdrawalApproval(ctx, req.(*GetWithdrawalApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.v1.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimateNetworkFee",
			Handler:    _TransactionService_EstimateNetworkFee_Handler,
		},
		{
			MethodName: "GetWithdrawalQuote",
			Handler:    _TransactionService_GetWithdrawalQuote_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _TransactionService_Withdraw_Handler,
		},
		{
			MethodName: "SweepUserWallet",
			Handler:    _TransactionService_SweepUserWallet_Handler,
		},
		{
			MethodName: "SweepAllUsers",
			Handler:    _TransactionService_SweepAllUsers_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _TransactionService_GetTransaction_Handler,
		},
		{
			MethodName: "GetUserTransactions",
			Handler:    _TransactionService_GetUserTransactions_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _TransactionService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetPendingWithdrawals",
			Handler:    _TransactionService_GetPendingWithdrawals_Handler,
		},
		{
			MethodName: "ApproveWithdrawal",
			Handler:    _TransactionService_ApproveWithdrawal_Handler,
		},
		{
			MethodName: "RejectWithdrawal",
			Handler:    _TransactionService_RejectWithdrawal_Handler,
		},
		{
			MethodName: "GetWithdrawalApproval",
			Handler:    _TransactionService_GetWithdrawalApproval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
