// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: proto/shared/accounting/receipt_v3.proto

package receiptpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReceiptService_CreateReceipt_FullMethodName        = "/accounting.receipt.v3.ReceiptService/CreateReceipt"
	ReceiptService_GetReceipt_FullMethodName           = "/accounting.receipt.v3.ReceiptService/GetReceipt"
	ReceiptService_UpdateReceipt_FullMethodName        = "/accounting.receipt.v3.ReceiptService/UpdateReceipt"
	ReceiptService_CreateReceiptsBatch_FullMethodName  = "/accounting.receipt.v3.ReceiptService/CreateReceiptsBatch"
	ReceiptService_GetReceiptsBatch_FullMethodName     = "/accounting.receipt.v3.ReceiptService/GetReceiptsBatch"
	ReceiptService_UpdateReceiptsBatch_FullMethodName  = "/accounting.receipt.v3.ReceiptService/UpdateReceiptsBatch"
	ReceiptService_CreateReceiptsStream_FullMethodName = "/accounting.receipt.v3.ReceiptService/CreateReceiptsStream"
	ReceiptService_UpdateReceiptsStream_FullMethodName = "/accounting.receipt.v3.ReceiptService/UpdateReceiptsStream"
	ReceiptService_ListReceipts_FullMethodName         = "/accounting.receipt.v3.ReceiptService/ListReceipts"
	ReceiptService_HealthCheck_FullMethodName          = "/accounting.receipt.v3.ReceiptService/HealthCheck"
	ReceiptService_GetMetrics_FullMethodName           = "/accounting.receipt.v3.ReceiptService/GetMetrics"
)

// ReceiptServiceClient is the client API for ReceiptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===============================
// Service Definition
// ===============================
type ReceiptServiceClient interface {
	// --- Single Operations ---
	CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*CreateReceiptResponse, error)
	GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error)
	UpdateReceipt(ctx context.Context, in *UpdateReceiptRequest, opts ...grpc.CallOption) (*UpdateReceiptResponse, error)
	// --- Batch Operations (High Performance) ---
	CreateReceiptsBatch(ctx context.Context, in *CreateReceiptsBatchRequest, opts ...grpc.CallOption) (*CreateReceiptsBatchResponse, error)
	GetReceiptsBatch(ctx context.Context, in *GetReceiptsRequest, opts ...grpc.CallOption) (*GetReceiptsResponse, error)
	UpdateReceiptsBatch(ctx context.Context, in *UpdateReceiptsBatchRequest, opts ...grpc.CallOption) (*UpdateReceiptsBatchResponse, error)
	// --- Streaming (for very high throughput) ---
	CreateReceiptsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateReceiptRequest, CreateReceiptResponse], error)
	UpdateReceiptsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateReceiptRequest, UpdateReceiptResponse], error)
	// --- Query ---
	ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error)
	// --- Health & Metrics ---
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type receiptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiptServiceClient(cc grpc.ClientConnInterface) ReceiptServiceClient {
	return &receiptServiceClient{cc}
}

func (c *receiptServiceClient) CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*CreateReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiptResponse)
	err := c.cc.Invoke(ctx, ReceiptService_CreateReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, ReceiptService_GetReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) UpdateReceipt(ctx context.Context, in *UpdateReceiptRequest, opts ...grpc.CallOption) (*UpdateReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReceiptResponse)
	err := c.cc.Invoke(ctx, ReceiptService_UpdateReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) CreateReceiptsBatch(ctx context.Context, in *CreateReceiptsBatchRequest, opts ...grpc.CallOption) (*CreateReceiptsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiptsBatchResponse)
	err := c.cc.Invoke(ctx, ReceiptService_CreateReceiptsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) GetReceiptsBatch(ctx context.Context, in *GetReceiptsRequest, opts ...grpc.CallOption) (*GetReceiptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReceiptsResponse)
	err := c.cc.Invoke(ctx, ReceiptService_GetReceiptsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) UpdateReceiptsBatch(ctx context.Context, in *UpdateReceiptsBatchRequest, opts ...grpc.CallOption) (*UpdateReceiptsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateReceiptsBatchResponse)
	err := c.cc.Invoke(ctx, ReceiptService_UpdateReceiptsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) CreateReceiptsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateReceiptRequest, CreateReceiptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReceiptService_ServiceDesc.Streams[0], ReceiptService_CreateReceiptsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateReceiptRequest, CreateReceiptResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReceiptService_CreateReceiptsStreamClient = grpc.BidiStreamingClient[CreateReceiptRequest, CreateReceiptResponse]

func (c *receiptServiceClient) UpdateReceiptsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateReceiptRequest, UpdateReceiptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReceiptService_ServiceDesc.Streams[1], ReceiptService_UpdateReceiptsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateReceiptRequest, UpdateReceiptResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReceiptService_UpdateReceiptsStreamClient = grpc.BidiStreamingClient[UpdateReceiptRequest, UpdateReceiptResponse]

func (c *receiptServiceClient) ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReceiptsResponse)
	err := c.cc.Invoke(ctx, ReceiptService_ListReceipts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ReceiptService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *receiptServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ReceiptService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiptServiceServer is the server API for ReceiptService service.
// All implementations must embed UnimplementedReceiptServiceServer
// for forward compatibility.
//
// ===============================
// Service Definition
// ===============================
type ReceiptServiceServer interface {
	// --- Single Operations ---
	CreateReceipt(context.Context, *CreateReceiptRequest) (*CreateReceiptResponse, error)
	GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error)
	UpdateReceipt(context.Context, *UpdateReceiptRequest) (*UpdateReceiptResponse, error)
	// --- Batch Operations (High Performance) ---
	CreateReceiptsBatch(context.Context, *CreateReceiptsBatchRequest) (*CreateReceiptsBatchResponse, error)
	GetReceiptsBatch(context.Context, *GetReceiptsRequest) (*GetReceiptsResponse, error)
	UpdateReceiptsBatch(context.Context, *UpdateReceiptsBatchRequest) (*UpdateReceiptsBatchResponse, error)
	// --- Streaming (for very high throughput) ---
	CreateReceiptsStream(grpc.BidiStreamingServer[CreateReceiptRequest, CreateReceiptResponse]) error
	UpdateReceiptsStream(grpc.BidiStreamingServer[UpdateReceiptRequest, UpdateReceiptResponse]) error
	// --- Query ---
	ListReceipts(context.Context, *ListReceiptsRequest) (*ListReceiptsResponse, error)
	// --- Health & Metrics ---
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedReceiptServiceServer()
}

// UnimplementedReceiptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReceiptServiceServer struct{}

func (UnimplementedReceiptServiceServer) CreateReceipt(context.Context, *CreateReceiptRequest) (*CreateReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceipt not implemented")
}
func (UnimplementedReceiptServiceServer) GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceipt not implemented")
}
func (UnimplementedReceiptServiceServer) UpdateReceipt(context.Context, *UpdateReceiptRequest) (*UpdateReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReceipt not implemented")
}
func (UnimplementedReceiptServiceServer) CreateReceiptsBatch(context.Context, *CreateReceiptsBatchRequest) (*CreateReceiptsBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceiptsBatch not implemented")
}
func (UnimplementedReceiptServiceServer) GetReceiptsBatch(context.Context, *GetReceiptsRequest) (*GetReceiptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceiptsBatch not implemented")
}
func (UnimplementedReceiptServiceServer) UpdateReceiptsBatch(context.Context, *UpdateReceiptsBatchRequest) (*UpdateReceiptsBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReceiptsBatch not implemented")
}
func (UnimplementedReceiptServiceServer) CreateReceiptsStream(grpc.BidiStreamingServer[CreateReceiptRequest, CreateReceiptResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CreateReceiptsStream not implemented")
}
func (UnimplementedReceiptServiceServer) UpdateReceiptsStream(grpc.BidiStreamingServer[UpdateReceiptRequest, UpdateReceiptResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateReceiptsStream not implemented")
}
func (UnimplementedReceiptServiceServer) ListReceipts(context.Context, *ListReceiptsRequest) (*ListReceiptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReceipts not implemented")
}
func (UnimplementedReceiptServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedReceiptServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedReceiptServiceServer) mustEmbedUnimplementedReceiptServiceServer() {}
func (UnimplementedReceiptServiceServer) testEmbeddedByValue()                        {}

// UnsafeReceiptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceiptServiceServer will
// result in compilation errors.
type UnsafeReceiptServiceServer interface {
	mustEmbedUnimplementedReceiptServiceServer()
}

func RegisterReceiptServiceServer(s grpc.ServiceRegistrar, srv ReceiptServiceServer) {
	// If the following call pancis, it indicates UnimplementedReceiptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReceiptService_ServiceDesc, srv)
}

func _ReceiptService_CreateReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).CreateReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_CreateReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).CreateReceipt(ctx, req.(*CreateReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_GetReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).GetReceipt(ctx, req.(*GetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_UpdateReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).UpdateReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_UpdateReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).UpdateReceipt(ctx, req.(*UpdateReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_CreateReceiptsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiptsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).CreateReceiptsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_CreateReceiptsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).CreateReceiptsBatch(ctx, req.(*CreateReceiptsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_GetReceiptsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).GetReceiptsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_GetReceiptsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).GetReceiptsBatch(ctx, req.(*GetReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_UpdateReceiptsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReceiptsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).UpdateReceiptsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_UpdateReceiptsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).UpdateReceiptsBatch(ctx, req.(*UpdateReceiptsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_CreateReceiptsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReceiptServiceServer).CreateReceiptsStream(&grpc.GenericServerStream[CreateReceiptRequest, CreateReceiptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReceiptService_CreateReceiptsStreamServer = grpc.BidiStreamingServer[CreateReceiptRequest, CreateReceiptResponse]

func _ReceiptService_UpdateReceiptsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReceiptServiceServer).UpdateReceiptsStream(&grpc.GenericServerStream[UpdateReceiptRequest, UpdateReceiptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReceiptService_UpdateReceiptsStreamServer = grpc.BidiStreamingServer[UpdateReceiptRequest, UpdateReceiptResponse]

func _ReceiptService_ListReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).ListReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_ListReceipts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).ListReceipts(ctx, req.(*ListReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReceiptService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiptServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReceiptService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiptServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReceiptService_ServiceDesc is the grpc.ServiceDesc for ReceiptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReceiptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounting.receipt.v3.ReceiptService",
	HandlerType: (*ReceiptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReceipt",
			Handler:    _ReceiptService_CreateReceipt_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _ReceiptService_GetReceipt_Handler,
		},
		{
			MethodName: "UpdateReceipt",
			Handler:    _ReceiptService_UpdateReceipt_Handler,
		},
		{
			MethodName: "CreateReceiptsBatch",
			Handler:    _ReceiptService_CreateReceiptsBatch_Handler,
		},
		{
			MethodName: "GetReceiptsBatch",
			Handler:    _ReceiptService_GetReceiptsBatch_Handler,
		},
		{
			MethodName: "UpdateReceiptsBatch",
			Handler:    _ReceiptService_UpdateReceiptsBatch_Handler,
		},
		{
			MethodName: "ListReceipts",
			Handler:    _ReceiptService_ListReceipts_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ReceiptService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ReceiptService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateReceiptsStream",
			Handler:       _ReceiptService_CreateReceiptsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateReceiptsStream",
			Handler:       _ReceiptService_UpdateReceiptsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/shared/accounting/receipt_v3.proto",
}
