-- Migration: Make agent_external_id the PRIMARY KEY for agents and link agent_commissions FK to it.
-- Fixed: avoid nested $$ quoting and ensure function creation is not inside DO $$ blocks.
-- Idempotent and safe to run multiple times. Test on staging and BACKUP before running in production.

\c pxyz_fx;

BEGIN;

-- 1) If legacy table exists and agents doesn't, rename it.
-- DO $$
-- BEGIN
--   IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'agent_relationships') THEN
--     IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'agents') THEN
--       ALTER TABLE agent_relationships RENAME TO agents;
--       RAISE NOTICE 'Renamed agent_relationships -> agents';
--     ELSE
--       RAISE NOTICE 'agents table already exists; skipping rename';
--     END IF;
--   END IF;
-- END$$;

DROP TABLE IF EXISTS agent_relationships;

-- 2) Create agents table if it does not exist, with agent_external_id as PRIMARY KEY
CREATE TABLE IF NOT EXISTS agents (
  agent_external_id    TEXT PRIMARY KEY,    -- Primary agent identifier (generated by app)
  user_external_id     TEXT UNIQUE,         -- auth user id for the agent (optional but unique)
  service              TEXT,               -- mpesa, bank, etc
  commission_rate      NUMERIC(5,4),
  relationship_type    TEXT DEFAULT 'direct',
  is_active            BOOLEAN NOT NULL DEFAULT true,
  synced_from_auth_at  TIMESTAMPTZ DEFAULT now(),
  name                 TEXT,
  metadata             JSONB DEFAULT '{}'::jsonb,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add commission_rate_for_deposit field
ALTER TABLE agents 
ADD COLUMN commission_rate_for_deposit NUMERIC(5,4);

-- Add payment_method field (dictionary/enum-like)
ALTER TABLE agents 
ADD COLUMN payment_method TEXT;

-- Add location field (dictionary stored as JSONB for country flags)
ALTER TABLE agents 
ADD COLUMN location JSONB DEFAULT '{}'::jsonb;

-- Add status field for soft delete tracking
ALTER TABLE agents 
ADD COLUMN status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'deleted'));

-- Add comment for clarity on location field
COMMENT ON COLUMN agents.location IS 'Dictionary of countries with boolean flags, e.g. {"KE": true, "UG": false}';

-- Add comment for payment_method
COMMENT ON COLUMN agents.payment_method IS 'Payment method type:  mpesa, bank, cash, etc. ';

-- Add comment for status
COMMENT ON COLUMN agents. status IS 'Status for tracking:  active, inactive, or deleted (soft delete)';
COMMENT ON TABLE agents IS 'Agent metadata (agent_external_id is primary key). user_external_id is the auth user id for the agent.';

-- 3) If agents exists but missing columns, add them (idempotent)
ALTER TABLE agents ADD COLUMN IF NOT EXISTS user_external_id TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS service TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(5,4);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS relationship_type TEXT DEFAULT 'direct';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS synced_from_auth_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE agents ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE agents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();


-- 5) Ensure user_external_id unique index exists for lookup by auth user id (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE tablename = 'agents' AND indexname = 'uq_agents_user_external_id'
  ) THEN
    CREATE UNIQUE INDEX uq_agents_user_external_id ON agents (user_external_id) WHERE user_external_id IS NOT NULL;
  END IF;
END$$;

-- 6) Create or replace update_updated_at_column() function (safe; idempotent)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $func$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$func$ LANGUAGE plpgsql;

-- Attach trigger to agents (drop if exists, then create)
DROP TRIGGER IF EXISTS trg_agents_updated_at ON agents;
CREATE TRIGGER trg_agents_updated_at
  BEFORE UPDATE ON agents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 7) If agent_commissions exists, ensure its agent_external_id values reference agents.agent_external_id.
--    Insert placeholder agents for any agent_external_id values in agent_commissions that are missing in agents,
--    then add FK constraint if it does not exist yet.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'agent_commissions') THEN

    -- insert placeholders only for missing agent_external_id values
    INSERT INTO agents (agent_external_id, created_at, updated_at, is_active)
    SELECT DISTINCT ac.agent_external_id, now(), now(), false
    FROM agent_commissions ac
    LEFT JOIN agents a ON a.agent_external_id = ac.agent_external_id
    WHERE ac.agent_external_id IS NOT NULL AND a.agent_external_id IS NULL;

    -- add FK if missing
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name AND tc.table_name = kcu.table_name
      WHERE tc.table_name = 'agent_commissions'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND kcu.column_name = 'agent_external_id'
    ) THEN
      ALTER TABLE agent_commissions
        ADD CONSTRAINT fk_agent_commissions_agent_external_id
        FOREIGN KEY (agent_external_id) REFERENCES agents (agent_external_id)
        ON UPDATE CASCADE ON DELETE RESTRICT;
      RAISE NOTICE 'Added FK agent_commissions.agent_external_id -> agents.agent_external_id';
    ELSE
      RAISE NOTICE 'FK on agent_commissions.agent_external_id already exists';
    END IF;
  ELSE
    RAISE NOTICE 'agent_commissions table does not exist; skipping FK creation';
  END IF;
END$$;

-- 8) Helpful indexes (idempotent)
CREATE INDEX IF NOT EXISTS idx_agents_active ON agents (is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_agents_service ON agents (service) WHERE service IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_commissions_agent ON agent_commissions (agent_external_id, created_at DESC);

COMMIT;