// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/shared/accounting/receipt_v2.proto

package receiptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Party Info (creditor/debitor)
type PartyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`      // FK -> accounts.id
	LedgerId      int64                  `protobuf:"varint,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`         // FK -> ledgers.id
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"` // user, partner, system
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                              // pending, success, failed
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	AccountNumber string                 `protobuf:"bytes,8,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"` // optional external identifier
	IsCreditor    bool                   `protobuf:"varint,9,opt,name=is_creditor,json=isCreditor,proto3" json:"is_creditor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInfo) Reset() {
	*x = PartyInfo{}
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInfo) ProtoMessage() {}

func (x *PartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInfo.ProtoReflect.Descriptor instead.
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP(), []int{0}
}

func (x *PartyInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PartyInfo) GetLedgerId() int64 {
	if x != nil {
		return x.LedgerId
	}
	return 0
}

func (x *PartyInfo) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *PartyInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PartyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartyInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PartyInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PartyInfo) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PartyInfo) GetIsCreditor() bool {
	if x != nil {
		return x.IsCreditor
	}
	return false
}

// Receipt
type Receipt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                            // unique receipt code
	Type        string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                            // deposit, withdrawal, transfer, conversion, admin_credit
	CodedType   string                 `protobuf:"bytes,4,opt,name=coded_type,json=codedType,proto3" json:"coded_type,omitempty"` // optional subtype (fee, cashback, etc.)
	Amount      float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency    string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ExternalRef string                 `protobuf:"bytes,7,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"` // bank txn id, blockchain tx hash, etc.
	Status      string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                              // pending, success, failed, reversed
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy   string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ReversedAt  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=reversed_at,json=reversedAt,proto3" json:"reversed_at,omitempty"`
	ReversedBy  string                 `protobuf:"bytes,13,opt,name=reversed_by,json=reversedBy,proto3" json:"reversed_by,omitempty"`
	Creditor    *PartyInfo             `protobuf:"bytes,14,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Debitor     *PartyInfo             `protobuf:"bytes,15,opt,name=debitor,proto3" json:"debitor,omitempty"`
	// Flexible metadata (e.g. channel, fees breakdown, device info)
	Metadata      *structpb.Struct `protobuf:"bytes,16,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Receipt) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Receipt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Receipt) GetCodedType() string {
	if x != nil {
		return x.CodedType
	}
	return ""
}

func (x *Receipt) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receipt) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Receipt) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Receipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Receipt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Receipt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Receipt) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Receipt) GetReversedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReversedAt
	}
	return nil
}

func (x *Receipt) GetReversedBy() string {
	if x != nil {
		return x.ReversedBy
	}
	return ""
}

func (x *Receipt) GetCreditor() *PartyInfo {
	if x != nil {
		return x.Creditor
	}
	return nil
}

func (x *Receipt) GetDebitor() *PartyInfo {
	if x != nil {
		return x.Debitor
	}
	return nil
}

func (x *Receipt) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ===============================
// Requests / Responses
// ===============================
type CreateReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CodedType     string                 `protobuf:"bytes,2,opt,name=coded_type,json=codedType,proto3" json:"coded_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,5,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Creditor      *PartyInfo             `protobuf:"bytes,6,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Debitor       *PartyInfo             `protobuf:"bytes,7,opt,name=debitor,proto3" json:"debitor,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiptRequest) Reset() {
	*x = CreateReceiptRequest{}
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptRequest) ProtoMessage() {}

func (x *CreateReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiptRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReceiptRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateReceiptRequest) GetCodedType() string {
	if x != nil {
		return x.CodedType
	}
	return ""
}

func (x *CreateReceiptRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateReceiptRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateReceiptRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *CreateReceiptRequest) GetCreditor() *PartyInfo {
	if x != nil {
		return x.Creditor
	}
	return nil
}

func (x *CreateReceiptRequest) GetDebitor() *PartyInfo {
	if x != nil {
		return x.Debitor
	}
	return nil
}

func (x *CreateReceiptRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateReceiptRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiptResponse) Reset() {
	*x = CreateReceiptResponse{}
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptResponse) ProtoMessage() {}

func (x *CreateReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptResponse.ProtoReflect.Descriptor instead.
func (*CreateReceiptResponse) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReceiptResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type GetReceiptByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptByCodeRequest) Reset() {
	*x = GetReceiptByCodeRequest{}
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptByCodeRequest) ProtoMessage() {}

func (x *GetReceiptByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptByCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiptByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_proto_shared_accounting_receipt_v2_proto protoreflect.FileDescriptor

const file_proto_shared_accounting_receipt_v2_proto_rawDesc = "" +
	"\n" +
	"(proto/shared/accounting/receipt_v2.proto\x12\x15accounting.receipt.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8a\x02\n" +
	"\tPartyInfo\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\x03R\bledgerId\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12%\n" +
	"\x0eaccount_number\x18\b \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vis_creditor\x18\t \x01(\bR\n" +
	"isCreditor\"\xf1\x04\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"coded_type\x18\x04 \x01(\tR\tcodedType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fexternal_ref\x18\a \x01(\tR\vexternalRef\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12;\n" +
	"\vreversed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reversedAt\x12\x1f\n" +
	"\vreversed_by\x18\r \x01(\tR\n" +
	"reversedBy\x12<\n" +
	"\bcreditor\x18\x0e \x01(\v2 .accounting.receipt.v2.PartyInfoR\bcreditor\x12:\n" +
	"\adebitor\x18\x0f \x01(\v2 .accounting.receipt.v2.PartyInfoR\adebitor\x123\n" +
	"\bmetadata\x18\x10 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xee\x02\n" +
	"\x14CreateReceiptRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"coded_type\x18\x02 \x01(\tR\tcodedType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fexternal_ref\x18\x05 \x01(\tR\vexternalRef\x12<\n" +
	"\bcreditor\x18\x06 \x01(\v2 .accounting.receipt.v2.PartyInfoR\bcreditor\x12:\n" +
	"\adebitor\x18\a \x01(\v2 .accounting.receipt.v2.PartyInfoR\adebitor\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\"Q\n" +
	"\x15CreateReceiptResponse\x128\n" +
	"\areceipt\x18\x01 \x01(\v2\x1e.accounting.receipt.v2.ReceiptR\areceipt\"-\n" +
	"\x17GetReceiptByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code2\xe2\x01\n" +
	"\x10ReceiptServiceV2\x12j\n" +
	"\rCreateReceipt\x12+.accounting.receipt.v2.CreateReceiptRequest\x1a,.accounting.receipt.v2.CreateReceiptResponse\x12b\n" +
	"\x10GetReceiptByCode\x12..accounting.receipt.v2.GetReceiptByCodeRequest\x1a\x1e.accounting.receipt.v2.ReceiptB1Z/genproto/shared/accounting/receipt/v2;receiptpbb\x06proto3"

var (
	file_proto_shared_accounting_receipt_v2_proto_rawDescOnce sync.Once
	file_proto_shared_accounting_receipt_v2_proto_rawDescData []byte
)

func file_proto_shared_accounting_receipt_v2_proto_rawDescGZIP() []byte {
	file_proto_shared_accounting_receipt_v2_proto_rawDescOnce.Do(func() {
		file_proto_shared_accounting_receipt_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shared_accounting_receipt_v2_proto_rawDesc), len(file_proto_shared_accounting_receipt_v2_proto_rawDesc)))
	})
	return file_proto_shared_accounting_receipt_v2_proto_rawDescData
}

var file_proto_shared_accounting_receipt_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shared_accounting_receipt_v2_proto_goTypes = []any{
	(*PartyInfo)(nil),               // 0: accounting.receipt.v2.PartyInfo
	(*Receipt)(nil),                 // 1: accounting.receipt.v2.Receipt
	(*CreateReceiptRequest)(nil),    // 2: accounting.receipt.v2.CreateReceiptRequest
	(*CreateReceiptResponse)(nil),   // 3: accounting.receipt.v2.CreateReceiptResponse
	(*GetReceiptByCodeRequest)(nil), // 4: accounting.receipt.v2.GetReceiptByCodeRequest
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 6: google.protobuf.Struct
}
var file_proto_shared_accounting_receipt_v2_proto_depIdxs = []int32{
	5,  // 0: accounting.receipt.v2.Receipt.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: accounting.receipt.v2.Receipt.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: accounting.receipt.v2.Receipt.reversed_at:type_name -> google.protobuf.Timestamp
	0,  // 3: accounting.receipt.v2.Receipt.creditor:type_name -> accounting.receipt.v2.PartyInfo
	0,  // 4: accounting.receipt.v2.Receipt.debitor:type_name -> accounting.receipt.v2.PartyInfo
	6,  // 5: accounting.receipt.v2.Receipt.metadata:type_name -> google.protobuf.Struct
	0,  // 6: accounting.receipt.v2.CreateReceiptRequest.creditor:type_name -> accounting.receipt.v2.PartyInfo
	0,  // 7: accounting.receipt.v2.CreateReceiptRequest.debitor:type_name -> accounting.receipt.v2.PartyInfo
	6,  // 8: accounting.receipt.v2.CreateReceiptRequest.metadata:type_name -> google.protobuf.Struct
	1,  // 9: accounting.receipt.v2.CreateReceiptResponse.receipt:type_name -> accounting.receipt.v2.Receipt
	2,  // 10: accounting.receipt.v2.ReceiptServiceV2.CreateReceipt:input_type -> accounting.receipt.v2.CreateReceiptRequest
	4,  // 11: accounting.receipt.v2.ReceiptServiceV2.GetReceiptByCode:input_type -> accounting.receipt.v2.GetReceiptByCodeRequest
	3,  // 12: accounting.receipt.v2.ReceiptServiceV2.CreateReceipt:output_type -> accounting.receipt.v2.CreateReceiptResponse
	1,  // 13: accounting.receipt.v2.ReceiptServiceV2.GetReceiptByCode:output_type -> accounting.receipt.v2.Receipt
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_shared_accounting_receipt_v2_proto_init() }
func file_proto_shared_accounting_receipt_v2_proto_init() {
	if File_proto_shared_accounting_receipt_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shared_accounting_receipt_v2_proto_rawDesc), len(file_proto_shared_accounting_receipt_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shared_accounting_receipt_v2_proto_goTypes,
		DependencyIndexes: file_proto_shared_accounting_receipt_v2_proto_depIdxs,
		MessageInfos:      file_proto_shared_accounting_receipt_v2_proto_msgTypes,
	}.Build()
	File_proto_shared_accounting_receipt_v2_proto = out.File
	file_proto_shared_accounting_receipt_v2_proto_goTypes = nil
	file_proto_shared_accounting_receipt_v2_proto_depIdxs = nil
}
