version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro_net

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service/secrets:/app/secrets:ro
      - ./uploads:/app/uploads
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
    networks:
      - micro_net
    depends_on:
      - redis

  session-service:
    container_name: session-service
    build:
      context: .
      dockerfile: services/session-mngt/Dockerfile
    ports:
      - "50050:50050"
    env_file:
      - ./services/session-mngt/.env
    volumes:
      - ./services/session-mngt/secrets:/app/secrets:ro
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    networks:
      - micro_net
    depends_on:
      - redis

  email-service:
    container_name: email-service
    build:
      context: .
      dockerfile: services/email-service/Dockerfile
    ports:
      - "50054:50054"
    env_file:
      - ./services/email-service/.env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      GRPCPort: 50054
      SMTPHost: smtp.gmail.com
      SMTPUser: anthonyalando8@gmail.com
      SMTPPort: 587
      SMTPPass: dqiadasrccjulcuh
    networks:
      - micro_net
    depends_on:
      - redis

  otp-service:
    container_name: otp-service
    build:
      context: .
      dockerfile: services/otp-service/Dockerfile
    ports:
      - "50055:50055"
    env_file:
      - ./services/otp-service/.env
    environment:
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      EMAIL_SVC_ADDR: email-service:50054
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net

  account-service:
    container_name: account-service
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    ports:
      - "50056:50056"
    env_file:
      - ./services/account-service/.env
    environment:
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      EMAIL_SVC_ADDR: email-service:50054
      GRPC_ADDR: 50056
      REDIS_PASS:
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net

  kyc-service:
    container_name: kyc-service
    build:
      context: .
      dockerfile: services/kyc-service/Dockerfile
    ports:
      - "50057:50057"
    env_file:
      - ./services/kyc-service/.env
    environment:
      HTTP_ADDR: :50057
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      REDIS_PASS:
      EMAIL_SVC_ADDR: email-service:50054
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    depends_on:
      - redis
      - email-service
    volumes:
      - ./services/kyc-service/secrets:/app/secrets:ro
      - ./uploads:/app/uploads
    networks:
      - micro_net

  cashier-service:
    container_name: cashier-service
    build:
      context: .
      dockerfile: services/cashier-service/Dockerfile
    ports:
      - "50058:50058"
    env_file:
      - ./services/cashier-service/.env
    environment:
      HTTP_ADDR: :50058
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      REDIS_PASS:
      JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
      JWT_AUDIENCE: pxyz-clients
      JWT_ISSUER: auth-service
      JWT_ACCESS_TTL: 5h
      MPESA_CONSUMER_KEY: WE0ODHDhooeTBWhIxIwbqM3L7cd9SSxTagXCrZhynGmwRiAp
      MPESA_CONSUMER_SECRET: fDLAvAoRFT6QBnKgrxNrUfA3Mozx0btGpm7DIGqVBfn44adGiDHtdKlJnJ9jbN1K
      MPESA_PASSKEY: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      MPESA_SHORT_CODE: 174379
      MPESA_TILL_NUMBER: 174379
    depends_on:
      - redis
      #- postgres
      - auth-service
    volumes:
      - ./services/cashier-service/secrets:/app/secrets:ro
    networks:
      - micro_net


networks:
  micro_net:
    driver: bridge
