version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro_net

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "8001:8001"
      - "8006:8006"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service/secrets:/app/secrets:ro
      - ./uploads:/app/uploads
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      SYSTEM_ADMIN_PASSWORD: 96211581#Aa
      SYSTEM_ADMIN_EMAIL: anthonyalando8@gmail.com
    networks:
      - micro_net
    depends_on:
      - redis

  session-service:
    container_name: session-service
    build:
      context: .
      dockerfile: services/session-mngt/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./services/session-mngt/.env
    volumes:
      - ./services/session-mngt/secrets:/app/secrets:ro
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    networks:
      - micro_net
    depends_on:
      - redis

  email-service:
    container_name: email-service
    build:
      context: .
      dockerfile: services/email-service/Dockerfile
    ports:
      - "8011:8011"
    env_file:
      - ./services/email-service/.env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      GRPCPort: :8011
      SMTPHost: smtp.gmail.com
      SMTPUser: anthonyalando8@gmail.com
      SMTPPort: 587
      SMTPPass: dqiadasrccjulcuh
    networks:
      - micro_net
    depends_on:
      - redis

  otp-service:
    container_name: otp-service
    build:
      context: .
      dockerfile: services/otp-service/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./services/otp-service/.env
    environment:
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      EMAIL_SVC_ADDR: email-service:8011
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net

  account-service:
    container_name: account-service
    build:
      context: .
      dockerfile: services/account-service/Dockerfile
    ports:
      - "8004:8004"
    env_file:
      - ./services/account-service/.env
    environment:
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      EMAIL_SVC_ADDR: email-service:8011
      GRPC_ADDR: :8004
      REDIS_PASS:
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net

  kyc-service:
    container_name: kyc-service
    build:
      context: .
      dockerfile: services/kyc-service/Dockerfile
    ports:
      - "8005:8005"
    env_file:
      - ./services/kyc-service/.env
    environment:
      HTTP_ADDR: :8005
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      REDIS_PASS:
      EMAIL_SVC_ADDR: email-service:8011
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    depends_on:
      - redis
      - email-service
    volumes:
      - ./services/kyc-service/secrets:/app/secrets:ro
      - ./uploads:/app/uploads
    networks:
      - micro_net

  cashier-service:
    container_name: cashier-service
    build:
      context: .
      dockerfile: services/cashier-service/Dockerfile
    ports:
      - "8021:8021"
    env_file:
      - ./services/cashier-service/.env
    environment:
      HTTP_ADDR: :8021
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      REDIS_PASS:
      JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
      JWT_AUDIENCE: pxyz-clients
      JWT_ISSUER: auth-service
      JWT_ACCESS_TTL: 5h
      MPESA_CONSUMER_KEY: WE0ODHDhooeTBWhIxIwbqM3L7cd9SSxTagXCrZhynGmwRiAp
      MPESA_CONSUMER_SECRET: fDLAvAoRFT6QBnKgrxNrUfA3Mozx0btGpm7DIGqVBfn44adGiDHtdKlJnJ9jbN1K
      MPESA_PASSKEY: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      MPESA_SHORT_CODE: 174379
      MPESA_TILL_NUMBER: 174379
    depends_on:
      - redis
      #- postgres
      - auth-service
    volumes:
      - ./services/cashier-service/secrets:/app/secrets:ro
    networks:
      - micro_net
  sms-service:
    container_name: sms-service
    build:
      context: .
      dockerfile: services/sms-service/Dockerfile
    ports:
      - "8012:8012"
    env_file:
      - ./services/sms-service/.env
    environment:
      GRPC_ADDR: :8012
      REDIS_PASS:
      SMS_KEY:
      WA_KEY:
      SMS_URL: https://smsportal.hostpinnacle.co.ke/SMSApi/send
      WA_URL: https://whatsappprovider.com/api
      SENDER: SENDER_ID
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
      USER_ID:
      PASSWORD:
      REDIS_ADDR: redis:6379
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net
  partner-service:
    container_name: partner-service
    build:
      context: .
      dockerfile: services/partner-service/Dockerfile
    ports:
      - "8041:8041" # HTTP
    env_file:
      - ./services/partner-service/.env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      HTTP_ADDR: :8041
      GRPC_ADDR: :8042
      REDIS_ADDR: redis:6379
      REDIS_PASS: ""
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    volumes:
      - ./services/partner-service/secrets:/app/secrets:ro
    depends_on:
      - redis
      - auth-service
    networks:
      - micro_net


networks:
  micro_net:
    driver: bridge
