version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - micro_net

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service/secrets:/app/secrets:ro
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
    networks:
      - micro_net
    depends_on:
      - redis

  session-service:
    container_name: session-service
    build:
      context: .
      dockerfile: services/session-mngt/Dockerfile
    ports:
      - "50050:50050"
    env_file:
      - ./services/session-mngt/.env
    volumes:
      - ./services/session-mngt/secrets:/app/secrets:ro
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private.pem
      JWT_PUBLIC_KEY_PATH: /app/secrets/jwt_public.pem
    networks:
      - micro_net
    depends_on:
      - redis

  email-service:
    container_name: email-service
    build:
      context: .
      dockerfile: services/email-service/Dockerfile
    ports:
      - "50054:50054"
    env_file:
      - ./services/email-service/.env
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 2000
      DB_NAME: pxyz
      REDIS_ADDR: redis:6379
      GRPCPort: 50054
      SMTPHost: smtp.gmail.com
      SMTPUser: anthonyalando8@gmail.com
      SMTPPort: 587
      SMTPPass: dqiadasrccjulcuh
    networks:
      - micro_net
    depends_on:
      - redis

  otp-service:
    container_name: otp-service
    build:
      context: .
      dockerfile: services/otp-service/Dockerfile
    ports:
      - "50055:50055"
    env_file:
      - ./services/otp-service/.env
    environment:
      DB_CONN: postgres://postgres:2000@host.docker.internal:5432/pxyz
      REDIS_ADDR: redis:6379
      EMAIL_SVC_ADDR: email-service:50054
    depends_on:
      - redis
      - email-service
    networks:
      - micro_net
networks:
  micro_net:
    driver: bridge
