package domain

import (
	"time"

	"github.com/shopspring/decimal"
)

// Agent is the domain model for the agents table. 
// agent_external_id is the canonical PK (generated by the application). 
// domain/agent.go
type Agent struct {
	AgentExternalID  string                 `json:"agent_external_id"`
	UserExternalID   *string                `json:"user_external_id,omitempty"`
	Service          *string                `json:"service,omitempty"`
	CommissionRate   *decimal.Decimal       `json:"commission_rate,omitempty"`
	RelationshipType string                 `json:"relationship_type,omitempty"`
	IsActive         bool                   `json:"is_active"`
	Name             *string                `json:"name,omitempty"`
	Metadata         map[string]interface{} `json:"metadata,omitempty"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
	Accounts         []*Account             `json:"accounts,omitempty"` // ✅ Added accounts field
}

// AgentCommission represents the agent_commissions row (NUMERIC amounts).
type AgentCommission struct {
	ID                int64           `json:"id"`
	AgentExternalID   string          `json:"agent_external_id"`
	UserExternalID    string          `json:"user_external_id"`
	AgentAccountID    int64           `json:"agent_account_id"`
	UserAccountID     int64           `json:"user_account_id"`
	ReceiptCode       string          `json:"receipt_code"`
	TransactionAmount decimal.Decimal `json:"transaction_amount"`
	CommissionRate    decimal.Decimal `json:"commission_rate"`
	CommissionAmount  decimal.Decimal `json:"commission_amount"`
	Currency          string          `json:"currency"`
	PaidOut           bool            `json:"paid_out"`
	PayoutReceiptCode string          `json:"payout_receipt_code,omitempty"`
	PaidOutAt         *time.Time      `json:"paid_out_at,omitempty"`
	CreatedAt         time.Time       `json:"created_at"`
}