// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/otp/otp.proto

package otppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`     // e.g. "login", "reset"
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`     // "email" or "sms"
	Recipient     string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"` // email address or phone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOTPRequest) Reset() {
	*x = GenerateOTPRequest{}
	mi := &file_proto_otp_otp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOTPRequest) ProtoMessage() {}

func (x *GenerateOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_otp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOTPRequest.ProtoReflect.Descriptor instead.
func (*GenerateOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_otp_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateOTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateOTPRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *GenerateOTPRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GenerateOTPRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type GenerateOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateOTPResponse) Reset() {
	*x = GenerateOTPResponse{}
	mi := &file_proto_otp_otp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateOTPResponse) ProtoMessage() {}

func (x *GenerateOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_otp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateOTPResponse.ProtoReflect.Descriptor instead.
func (*GenerateOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_otp_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateOTPResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GenerateOTPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_proto_otp_otp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_otp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_otp_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyOTPRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyOTPRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *VerifyOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	mi := &file_proto_otp_otp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_otp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_otp_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOTPResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyOTPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_otp_otp_proto protoreflect.FileDescriptor

const file_proto_otp_otp_proto_rawDesc = "" +
	"\n" +
	"\x13proto/otp/otp.proto\x12\x03otp\"\x7f\n" +
	"\x12GenerateOTPRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\";\n" +
	"\x13GenerateOTPResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\x10VerifyOTPRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"?\n" +
	"\x11VerifyOTPResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x8a\x01\n" +
	"\n" +
	"OTPService\x12@\n" +
	"\vGenerateOTP\x12\x17.otp.GenerateOTPRequest\x1a\x18.otp.GenerateOTPResponse\x12:\n" +
	"\tVerifyOTP\x12\x15.otp.VerifyOTPRequest\x1a\x16.otp.VerifyOTPResponseB\x16Z\x14genproto/otppb;otppbb\x06proto3"

var (
	file_proto_otp_otp_proto_rawDescOnce sync.Once
	file_proto_otp_otp_proto_rawDescData []byte
)

func file_proto_otp_otp_proto_rawDescGZIP() []byte {
	file_proto_otp_otp_proto_rawDescOnce.Do(func() {
		file_proto_otp_otp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_otp_otp_proto_rawDesc), len(file_proto_otp_otp_proto_rawDesc)))
	})
	return file_proto_otp_otp_proto_rawDescData
}

var file_proto_otp_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_otp_otp_proto_goTypes = []any{
	(*GenerateOTPRequest)(nil),  // 0: otp.GenerateOTPRequest
	(*GenerateOTPResponse)(nil), // 1: otp.GenerateOTPResponse
	(*VerifyOTPRequest)(nil),    // 2: otp.VerifyOTPRequest
	(*VerifyOTPResponse)(nil),   // 3: otp.VerifyOTPResponse
}
var file_proto_otp_otp_proto_depIdxs = []int32{
	0, // 0: otp.OTPService.GenerateOTP:input_type -> otp.GenerateOTPRequest
	2, // 1: otp.OTPService.VerifyOTP:input_type -> otp.VerifyOTPRequest
	1, // 2: otp.OTPService.GenerateOTP:output_type -> otp.GenerateOTPResponse
	3, // 3: otp.OTPService.VerifyOTP:output_type -> otp.VerifyOTPResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_otp_otp_proto_init() }
func file_proto_otp_otp_proto_init() {
	if File_proto_otp_otp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_otp_otp_proto_rawDesc), len(file_proto_otp_otp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_otp_otp_proto_goTypes,
		DependencyIndexes: file_proto_otp_otp_proto_depIdxs,
		MessageInfos:      file_proto_otp_otp_proto_msgTypes,
	}.Build()
	File_proto_otp_otp_proto = out.File
	file_proto_otp_otp_proto_goTypes = nil
	file_proto_otp_otp_proto_depIdxs = nil
}
