// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: proto/sms/sms.proto

package smswhatsapppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMSWhatsAppService_SendMessage_FullMethodName = "/smswhatsapp.SMSWhatsAppService/SendMessage"
)

// SMSWhatsAppServiceClient is the client API for SMSWhatsAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SMSWhatsAppServiceClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type sMSWhatsAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSMSWhatsAppServiceClient(cc grpc.ClientConnInterface) SMSWhatsAppServiceClient {
	return &sMSWhatsAppServiceClient{cc}
}

func (c *sMSWhatsAppServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, SMSWhatsAppService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSWhatsAppServiceServer is the server API for SMSWhatsAppService service.
// All implementations must embed UnimplementedSMSWhatsAppServiceServer
// for forward compatibility.
type SMSWhatsAppServiceServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedSMSWhatsAppServiceServer()
}

// UnimplementedSMSWhatsAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMSWhatsAppServiceServer struct{}

func (UnimplementedSMSWhatsAppServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedSMSWhatsAppServiceServer) mustEmbedUnimplementedSMSWhatsAppServiceServer() {}
func (UnimplementedSMSWhatsAppServiceServer) testEmbeddedByValue()                            {}

// UnsafeSMSWhatsAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMSWhatsAppServiceServer will
// result in compilation errors.
type UnsafeSMSWhatsAppServiceServer interface {
	mustEmbedUnimplementedSMSWhatsAppServiceServer()
}

func RegisterSMSWhatsAppServiceServer(s grpc.ServiceRegistrar, srv SMSWhatsAppServiceServer) {
	// If the following call pancis, it indicates UnimplementedSMSWhatsAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMSWhatsAppService_ServiceDesc, srv)
}

func _SMSWhatsAppService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSWhatsAppServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMSWhatsAppService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSWhatsAppServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMSWhatsAppService_ServiceDesc is the grpc.ServiceDesc for SMSWhatsAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMSWhatsAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smswhatsapp.SMSWhatsAppService",
	HandlerType: (*SMSWhatsAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _SMSWhatsAppService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sms/sms.proto",
}
