version: "3.9"

networks:
  micro_net:
    driver: bridge

services:
  postgres-master:
    image: public.ecr.aws/bitnami/postgresql-repmgr:16.4.0
    container_name: postgres-master
    hostname: postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=2000
      - POSTGRESQL_POSTGRES_PASSWORD=2000
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=2000
      - POSTGRESQL_DATABASE=pxyz
      
      - REPMGR_PRIMARY_HOST=postgres-master
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NAME=node-1
      - REPMGR_NODE_NETWORK_NAME=postgres-master
      - REPMGR_PARTNER_NODES=postgres-master,postgres-replica1,postgres-replica2,postgres-replica3
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=2000
      - REPMGR_DATABASE=repmgr
    volumes:
      - ./pgdata/auth/master:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - micro_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  postgres-replica1:
    image: public.ecr.aws/bitnami/postgresql-repmgr:16.4.0
    container_name: postgres-replica1
    hostname: postgres-replica1
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=2000
      - POSTGRESQL_PASSWORD=2000
      - REPMGR_PRIMARY_HOST=postgres-master
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NAME=node-2
      - REPMGR_NODE_NETWORK_NAME=postgres-replica1
      - REPMGR_PARTNER_NODES=postgres-master,postgres-replica1,postgres-replica2,postgres-replica3
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=2000
      - REPMGR_DATABASE=repmgr
    volumes:
      - ./pgdata/auth/replica1:/bitnami/postgresql
    ports:
      - "5433:5432"
    networks:
      - micro_net
    depends_on:
      postgres-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-replica2:
    image: public.ecr.aws/bitnami/postgresql-repmgr:16.4.0
    container_name: postgres-replica2
    hostname: postgres-replica2
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=2000
      - POSTGRESQL_PASSWORD=2000
      - REPMGR_PRIMARY_HOST=postgres-master
      - REPMGR_NODE_ID=3
      - REPMGR_NODE_NAME=node-3
      - REPMGR_NODE_NETWORK_NAME=postgres-replica2
      - REPMGR_PARTNER_NODES=postgres-master,postgres-replica1,postgres-replica2,postgres-replica3
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=2000
      - REPMGR_DATABASE=repmgr
    volumes:
      - ./pgdata/auth/replica2:/bitnami/postgresql
    ports:
      - "5434:5432"
    networks:
      - micro_net
    depends_on:
      postgres-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-replica3:
    image: public.ecr.aws/bitnami/postgresql-repmgr:16.4.0
    container_name: postgres-replica3
    hostname: postgres-replica3
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=2000
      - POSTGRESQL_PASSWORD=2000
      - REPMGR_PRIMARY_HOST=postgres-master
      - REPMGR_NODE_ID=4
      - REPMGR_NODE_NAME=node-4
      - REPMGR_NODE_NETWORK_NAME=postgres-replica3
      - REPMGR_PARTNER_NODES=postgres-master,postgres-replica1,postgres-replica2,postgres-replica3
      - REPMGR_USERNAME=repmgr
      - REPMGR_PASSWORD=2000
      - REPMGR_DATABASE=repmgr
    volumes:
      - ./pgdata/auth/replica3:/bitnami/postgresql
    ports:
      - "5436:5432"
    networks:
      - micro_net
    depends_on:
      postgres-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgpool:
    image: public.ecr.aws/bitnami/pgpool:4.5.2
    container_name: pgpool
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres-master:5432,1:postgres-replica1:5432,2:postgres-replica2:5432,3:postgres-replica3:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=2000
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=2000
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=2000
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_SKIP_PASSWORD_ENCRYPTION=yes

      - PGPOOL_HEALTH_CHECK_PERIOD=10
      - PGPOOL_HEALTH_CHECK_TIMEOUT=30
      - PGPOOL_HEALTH_CHECK_MAX_RETRIES=5
      - PGPOOL_HEALTH_CHECK_RETRY_DELAY=5

    volumes:
      - ./wait-for-replicas.sh:/docker-entrypoint-initdb.d/wait-for-replicas.sh
    ports:
      - "5435:5432"
    networks:
      - micro_net
    depends_on:
      - postgres-master
      - postgres-replica1
      - postgres-replica2
      - postgres-replica3
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -p 5432 -U postgres -d postgres -c 'SELECT 1;' || exit 1"]
      interval: 10s
      retries: 20
