# k8s/deployments/audit-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: YOUR_REGISTRY/audit-service:latest
        ports:
        - containerPort: 8008
        - containerPort: 8007
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: HTTP_ADDR
          value: ":8008"
        - name: GRPC_ADDR
          value: ":8007"
        volumeMounts:
        - name: jwt-keys
          mountPath: /app/secrets
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-secret