# k8s/deployments/notification-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: YOUR_REGISTRY/notification-service:latest
        ports:
        - containerPort: 8013
        - containerPort: 8014
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: HTTP_ADDR
          value: ":8013"
        - name: GRPC_ADDR
          value: ":8014"
        volumeMounts:
        - name: jwt-keys
          mountPath: /app/secrets
          readOnly: true
        - name: templates
          mountPath: /app/templates
          readOnly: true
        - name: uploads
          mountPath: /app/uploads
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-secret
      - name: templates
        configMap:
          name: notification-templates
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc