# k8s/deployments/otp-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otp-service
  template:
    metadata:
      labels:
        app: otp-service
    spec:
      containers:
      - name: otp-service
        image: YOUR_REGISTRY/otp-service:latest
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: connection-string
        - name: EMAIL_SVC_ADDR
          value: "email-service:8011"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"