# k8s/deployments/sms-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
    spec:
      containers:
      - name: sms-service
        image: YOUR_REGISTRY/sms-service:latest
        ports:
        - containerPort: 8012
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: GRPC_ADDR
          value: ":8012"
        - name: WA_KEY
          valueFrom:
            secretKeyRef:
              name: sms-secret
              key: wa-key
        - name: WA_URL
          value: "https://www.whatsupsender.co.ke"
        - name: WA_SENDER
          value: "254792207010"
        - name: SMS_URL
          value: "https://smsportal.hostpinnacle.co.ke/SMSApi/send"
        - name: SENDER
          value: "DERINANCE"
        - name: USER_ID
          value: "samderinance"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sms-secret
              key: sms-password
        volumeMounts:
        - name: jwt-keys
          mountPath: /app/secrets
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-secret