# k8s/deployments/u-access-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: u-access-service
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: u-access-service
  template:
    metadata:
      labels:
        app: u-access-service
    spec:
      containers:
      - name: u-access-service
        image: YOUR_REGISTRY/u-access-service:latest
        ports:
        - containerPort: 8031
        - containerPort: 8032
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: HTTP_ADDR
          value: ":8031"
        - name: GRPC_ADDR
          value: ":8032"
        volumeMounts:
        - name: jwt-keys
          mountPath: /app/secrets
          readOnly: true
        - name: uploads
          mountPath: /app/uploads
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: jwt-keys
        secret:
          secretName: jwt-secret
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc