// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/shared/accounting/receipt.proto

package receiptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nested message for creditor/debitor info
type PartyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // user, partner, system
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AccountNumber string                 `protobuf:"bytes,6,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"` // optional: account identifier
	IsCreditor    bool                   `protobuf:"varint,7,opt,name=is_creditor,json=isCreditor,proto3" json:"is_creditor,omitempty"`         // true if this party is the creditor, false if debitor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInfo) Reset() {
	*x = PartyInfo{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInfo) ProtoMessage() {}

func (x *PartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInfo.ProtoReflect.Descriptor instead.
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *PartyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PartyInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PartyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartyInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PartyInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PartyInfo) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PartyInfo) GetIsCreditor() bool {
	if x != nil {
		return x.IsCreditor
	}
	return false
}

// Main receipt message
type Receipt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code        string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	JournalId   int64                  `protobuf:"varint,3,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	AccountId   int64                  `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Type        string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Amount      float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency    string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Status      string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Creditor    *PartyInfo             `protobuf:"bytes,11,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Debitor     *PartyInfo             `protobuf:"bytes,12,opt,name=debitor,proto3" json:"debitor,omitempty"`
	CodedType   string                 `protobuf:"bytes,13,opt,name=coded_type,json=codedType,proto3" json:"coded_type,omitempty"`
	ExternalRef string                 `protobuf:"bytes,14,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	// Optional payload for notifications (flexible key-value map)
	Payload       *structpb.Struct `protobuf:"bytes,15,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Receipt) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Receipt) GetJournalId() int64 {
	if x != nil {
		return x.JournalId
	}
	return 0
}

func (x *Receipt) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Receipt) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Receipt) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Receipt) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receipt) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Receipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Receipt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Receipt) GetCreditor() *PartyInfo {
	if x != nil {
		return x.Creditor
	}
	return nil
}

func (x *Receipt) GetDebitor() *PartyInfo {
	if x != nil {
		return x.Debitor
	}
	return nil
}

func (x *Receipt) GetCodedType() string {
	if x != nil {
		return x.CodedType
	}
	return ""
}

func (x *Receipt) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Receipt) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Request message to create a receipt
type CreateReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JournalId     int64                  `protobuf:"varint,1,opt,name=journal_id,json=journalId,proto3" json:"journal_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	CodedType     string                 `protobuf:"bytes,7,opt,name=coded_type,json=codedType,proto3" json:"coded_type,omitempty"`
	ExternalRef   string                 `protobuf:"bytes,8,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Creditor      *PartyInfo             `protobuf:"bytes,9,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Debitor       *PartyInfo             `protobuf:"bytes,10,opt,name=debitor,proto3" json:"debitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiptRequest) Reset() {
	*x = CreateReceiptRequest{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptRequest) ProtoMessage() {}

func (x *CreateReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiptRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReceiptRequest) GetJournalId() int64 {
	if x != nil {
		return x.JournalId
	}
	return 0
}

func (x *CreateReceiptRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateReceiptRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateReceiptRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateReceiptRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateReceiptRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateReceiptRequest) GetCodedType() string {
	if x != nil {
		return x.CodedType
	}
	return ""
}

func (x *CreateReceiptRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *CreateReceiptRequest) GetCreditor() *PartyInfo {
	if x != nil {
		return x.Creditor
	}
	return nil
}

func (x *CreateReceiptRequest) GetDebitor() *PartyInfo {
	if x != nil {
		return x.Debitor
	}
	return nil
}

// Response message after creating a receipt
type CreateReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipt       *Receipt               `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiptResponse) Reset() {
	*x = CreateReceiptResponse{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiptResponse) ProtoMessage() {}

func (x *CreateReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiptResponse.ProtoReflect.Descriptor instead.
func (*CreateReceiptResponse) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReceiptResponse) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

// Additional requests/responses for optional RPCs
type GetReceiptByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReceiptByCodeRequest) Reset() {
	*x = GetReceiptByCodeRequest{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptByCodeRequest) ProtoMessage() {}

func (x *GetReceiptByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptByCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{4}
}

func (x *GetReceiptByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListReceiptsByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceiptsByAccountRequest) Reset() {
	*x = ListReceiptsByAccountRequest{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceiptsByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiptsByAccountRequest) ProtoMessage() {}

func (x *ListReceiptsByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiptsByAccountRequest.ProtoReflect.Descriptor instead.
func (*ListReceiptsByAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{5}
}

func (x *ListReceiptsByAccountRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ListReceiptsByAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receipts      []*Receipt             `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceiptsByAccountResponse) Reset() {
	*x = ListReceiptsByAccountResponse{}
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceiptsByAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceiptsByAccountResponse) ProtoMessage() {}

func (x *ListReceiptsByAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shared_accounting_receipt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceiptsByAccountResponse.ProtoReflect.Descriptor instead.
func (*ListReceiptsByAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_shared_accounting_receipt_proto_rawDescGZIP(), []int{6}
}

func (x *ListReceiptsByAccountResponse) GetReceipts() []*Receipt {
	if x != nil {
		return x.Receipts
	}
	return nil
}

var File_proto_shared_accounting_receipt_proto protoreflect.FileDescriptor

const file_proto_shared_accounting_receipt_proto_rawDesc = "" +
	"\n" +
	"%proto/shared/accounting/receipt.proto\x12\treceiptpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb7\x01\n" +
	"\tPartyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12%\n" +
	"\x0eaccount_number\x18\x06 \x01(\tR\raccountNumber\x12\x1f\n" +
	"\vis_creditor\x18\a \x01(\bR\n" +
	"isCreditor\"\x80\x04\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x03 \x01(\x03R\tjournalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x120\n" +
	"\bcreditor\x18\v \x01(\v2\x14.receiptpb.PartyInfoR\bcreditor\x12.\n" +
	"\adebitor\x18\f \x01(\v2\x14.receiptpb.PartyInfoR\adebitor\x12\x1d\n" +
	"\n" +
	"coded_type\x18\r \x01(\tR\tcodedType\x12!\n" +
	"\fexternal_ref\x18\x0e \x01(\tR\vexternalRef\x121\n" +
	"\apayload\x18\x0f \x01(\v2\x17.google.protobuf.StructR\apayload\"\xe3\x02\n" +
	"\x14CreateReceiptRequest\x12\x1d\n" +
	"\n" +
	"journal_id\x18\x01 \x01(\x03R\tjournalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"coded_type\x18\a \x01(\tR\tcodedType\x12!\n" +
	"\fexternal_ref\x18\b \x01(\tR\vexternalRef\x120\n" +
	"\bcreditor\x18\t \x01(\v2\x14.receiptpb.PartyInfoR\bcreditor\x12.\n" +
	"\adebitor\x18\n" +
	" \x01(\v2\x14.receiptpb.PartyInfoR\adebitor\"E\n" +
	"\x15CreateReceiptResponse\x12,\n" +
	"\areceipt\x18\x01 \x01(\v2\x12.receiptpb.ReceiptR\areceipt\"-\n" +
	"\x17GetReceiptByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"=\n" +
	"\x1cListReceiptsByAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"O\n" +
	"\x1dListReceiptsByAccountResponse\x12.\n" +
	"\breceipts\x18\x01 \x03(\v2\x12.receiptpb.ReceiptR\breceipts2\x9c\x02\n" +
	"\x0eReceiptService\x12R\n" +
	"\rCreateReceipt\x12\x1f.receiptpb.CreateReceiptRequest\x1a .receiptpb.CreateReceiptResponse\x12J\n" +
	"\x10GetReceiptByCode\x12\".receiptpb.GetReceiptByCodeRequest\x1a\x12.receiptpb.Receipt\x12j\n" +
	"\x15ListReceiptsByAccount\x12'.receiptpb.ListReceiptsByAccountRequest\x1a(.receiptpb.ListReceiptsByAccountResponseB0Z.genproto/shared/accounting/receiptpb;receiptpbb\x06proto3"

var (
	file_proto_shared_accounting_receipt_proto_rawDescOnce sync.Once
	file_proto_shared_accounting_receipt_proto_rawDescData []byte
)

func file_proto_shared_accounting_receipt_proto_rawDescGZIP() []byte {
	file_proto_shared_accounting_receipt_proto_rawDescOnce.Do(func() {
		file_proto_shared_accounting_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shared_accounting_receipt_proto_rawDesc), len(file_proto_shared_accounting_receipt_proto_rawDesc)))
	})
	return file_proto_shared_accounting_receipt_proto_rawDescData
}

var file_proto_shared_accounting_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_shared_accounting_receipt_proto_goTypes = []any{
	(*PartyInfo)(nil),                     // 0: receiptpb.PartyInfo
	(*Receipt)(nil),                       // 1: receiptpb.Receipt
	(*CreateReceiptRequest)(nil),          // 2: receiptpb.CreateReceiptRequest
	(*CreateReceiptResponse)(nil),         // 3: receiptpb.CreateReceiptResponse
	(*GetReceiptByCodeRequest)(nil),       // 4: receiptpb.GetReceiptByCodeRequest
	(*ListReceiptsByAccountRequest)(nil),  // 5: receiptpb.ListReceiptsByAccountRequest
	(*ListReceiptsByAccountResponse)(nil), // 6: receiptpb.ListReceiptsByAccountResponse
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),               // 8: google.protobuf.Struct
}
var file_proto_shared_accounting_receipt_proto_depIdxs = []int32{
	7,  // 0: receiptpb.Receipt.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: receiptpb.Receipt.creditor:type_name -> receiptpb.PartyInfo
	0,  // 2: receiptpb.Receipt.debitor:type_name -> receiptpb.PartyInfo
	8,  // 3: receiptpb.Receipt.payload:type_name -> google.protobuf.Struct
	0,  // 4: receiptpb.CreateReceiptRequest.creditor:type_name -> receiptpb.PartyInfo
	0,  // 5: receiptpb.CreateReceiptRequest.debitor:type_name -> receiptpb.PartyInfo
	1,  // 6: receiptpb.CreateReceiptResponse.receipt:type_name -> receiptpb.Receipt
	1,  // 7: receiptpb.ListReceiptsByAccountResponse.receipts:type_name -> receiptpb.Receipt
	2,  // 8: receiptpb.ReceiptService.CreateReceipt:input_type -> receiptpb.CreateReceiptRequest
	4,  // 9: receiptpb.ReceiptService.GetReceiptByCode:input_type -> receiptpb.GetReceiptByCodeRequest
	5,  // 10: receiptpb.ReceiptService.ListReceiptsByAccount:input_type -> receiptpb.ListReceiptsByAccountRequest
	3,  // 11: receiptpb.ReceiptService.CreateReceipt:output_type -> receiptpb.CreateReceiptResponse
	1,  // 12: receiptpb.ReceiptService.GetReceiptByCode:output_type -> receiptpb.Receipt
	6,  // 13: receiptpb.ReceiptService.ListReceiptsByAccount:output_type -> receiptpb.ListReceiptsByAccountResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_shared_accounting_receipt_proto_init() }
func file_proto_shared_accounting_receipt_proto_init() {
	if File_proto_shared_accounting_receipt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shared_accounting_receipt_proto_rawDesc), len(file_proto_shared_accounting_receipt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shared_accounting_receipt_proto_goTypes,
		DependencyIndexes: file_proto_shared_accounting_receipt_proto_depIdxs,
		MessageInfos:      file_proto_shared_accounting_receipt_proto_msgTypes,
	}.Build()
	File_proto_shared_accounting_receipt_proto = out.File
	file_proto_shared_accounting_receipt_proto_goTypes = nil
	file_proto_shared_accounting_receipt_proto_depIdxs = nil
}
