# k8s/services/account-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: microservices
spec:
  selector:
    app: account-service
  ports:
  - port: 8004
    targetPort: 8004