# k8s/services/audit-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: microservices
spec:
  selector:
    app: audit-service
  ports:
  - name: http
    port: 8008
    targetPort: 8008
  - name: grpc
    port: 8007
    targetPort: 8007