# k8s/services/email-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: microservices
spec:
  selector:
    app: email-service
  ports:
  - port: 8011
    targetPort: 8011