# k8s/services/kafka-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: microservices
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092