# k8s/services/redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: microservices
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379