# k8s/services/sms-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: microservices
spec:
  selector:
    app: sms-service
  ports:
  - port: 8012
    targetPort: 8012