# k8s/services/u-access-service-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: u-access-service
  namespace: microservices
spec:
  selector:
    app: u-access-service
  ports:
  - name: http
    port: 8031
    targetPort: 8031
  - name: grpc
    port: 8032
    targetPort: 8032